export const productosGym = [
  {
    id: 1,
    precio: 30,
    nombre: 'Mancuernas 5kg',
    descripcion: 'Mancuernas 5kg, perfectas para ejercicios ligeros',
    propiedades: {
      Material: 'Acero inoxidable',
      Color: 'Negro',
    },
    img: './assets/shop/mancuernas5.webp',
    cantidad: 1,
    alt: 'marcuernas 5 kilos',
  },
  {
    id: 2,
    precio: 11.99,
    nombre: 'Proteína en polvo',
    descripcion: 'Proteina "Gold Standard Whey" 400g',
    img: './assets/shop/protein.webp',
    propiedades: {
      Cantidad: '400g',
    },
    cantidad: 1,
    alt: 'proteina',
  },
  {
    id: 3,
    precio: 14.99,
    nombre: 'Banda de resistencia',
    descripcion: 'Banda elástica para ejercicios a diferentes intensidades',
    propiedades: {
      Niveles: 'Ligero, Medio, Fuerte',
      Color: 'Verde, Rojo, Negro, Morado',
    },
    img: './assets/shop/resistanceBand.png',
    cantidad: 1,
    alt: 'Banda de resistencia',
  },
  {
    id: 4,
    precio: 90,
    nombre: 'Barra olímpica',
    descripcion: 'Barra olímpica de 20kg',
    propiedades: {
      Material: 'Acero cromado',
      Longitud: '220 cm',
    },
    img: './assets/shop/barraOlimpica.jpg',
    cantidad: 1,
    alt: 'Barra olímpica',
  },
  {
    id: 5,
    precio: 10,
    nombre: 'Cuerda para saltar',
    descripcion: 'Comba regulable para entrenamiento cardiovascular',
    propiedades: {
      Material: 'Cable de acero',
      Longitud: '3 metros',
    },
    img: './assets/shop/comba.webp',
    cantidad: 1,
    alt: 'Cuerda para saltar',
  },
  {
    id: 6,
    precio: 249.99,
    nombre: 'Set de pesas ajustables',
    descripcion: 'Set de pesas ajustables con mecanismo de engranajes',
    propiedades: {
      Material: 'Hierro fundido',
      Peso: '2,5-24 kg',
    },
    img: './assets/shop/pesasAjustables.jpg',
    cantidad: 1,
    alt: 'Set de pesas ajustables',
  },
  {
    id: 7,
    precio: 8,
    nombre: 'Colchoneta de yoga',
    descripcion: 'Colchoneta antideslizante para práctica de yoga',
    propiedades: {
      Material: 'Goma espuma',
      Dimensiones: '183 x 61 cm',
    },
    img: './assets/shop/colchonetaYoga.webp',
    cantidad: 1,
    alt: 'Colchoneta de yoga',
  },
  {
    id: 8,
    precio: 12.99,
    nombre: 'Guantes de levantamiento',
    descripcion: 'Guantes acolchados para proteger las manos',
    propiedades: {
      Material: 'Cuero sintético',
      Tallas: 'S, M, L',
    },
    img: './assets/shop/guantes.jpg',
    cantidad: 1,
    alt: 'Guantes de levantamiento de pesas',
  },
  {
    id: 9,
    precio: 120,
    nombre: 'Cinta de correr plegable',
    descripcion: 'Cinta de correr plegable para entrenamientos en casa',
    img: './assets/shop/cintaCorrer.webp',
    propiedades: {
      Peso: '25kg',
    },
    cantidad: 1,
    alt: 'cinta de correr',
  },
  {
    id: 10,
    precio: 100,
    nombre: 'Banco de pesas ajustable',
    descripcion: 'Banco de pesas ajustable para entrenamientos diversos',
    img: './assets/shop/bancoAjustable.webp',
    propiedades: {
      Peso: '15kg',
    },
    cantidad: 1,
    alt: 'banco de pesas',
  },
  {
    id: 11,
    precio: 4.99,
    nombre: 'Rodillo de espuma',
    descripcion: 'Rodillo de espuma para liberación miofascial y recuperación muscular',
    propiedades: {
      Material: 'Espuma de alta densidad',
      Dimensiones: '30 x 15 cm',
    },
    img: './assets/shop/rodilloEspuma.webp',
    cantidad: 1,
    alt: 'Rodillo de espuma',
  },
  {
    id: 12,
    precio: 19.99,
    nombre: 'Creatina',
    descripcion: 'Creatina en polvo, suplemento con sello "Creapure", aumenta tu fuerza y energía',
    propiedades: {
      Cantidad: '300g',
    },
    img: './assets/shop/creatina.webp',
    cantidad: 1,
    alt: 'Creatina',
  },
];
